version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure_backend
    restart: always
    environment:
      - MONGO_URL=http://127.0.0.1:27017/securedb
      - JWT_SECRET=petitedouceur
    depends_on:
      - mongodb
    networks:
      - secure_network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secure_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - secure_network
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 30s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: secure_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - secure_network
    ports:
      - "27017:27017"
    command: ["--bind_ip_all", "--auth"]

networks:
  secure_network:
    driver: bridge

volumes:
  mongo_data:
